### ISSUE TITLE
Request for Pre-trained Model Weights

### ISSUE THREAD

**Issue by hoangsavitar** [Mamadou-Keita/VLM-DETECT#2]
I have been following your work and I'm particularly interested in the model you've developed. I was wondering if you could kindly provide the pre-trained weights for the model? It would be extremely helpful for my research as it would save me from having to retrain the model from scratch.
Looking forward to your response. Thank you for your time and consideration.

**Comment by Mamadou-Keita** [comment]
We have already provided the BLIP2 weight (refer to the SaveFineTune folder), or do you need the weights for all models (like ResNet, Xception etc...)?

**Comment by hoangsavitar** [comment]
Thanks for your reply, i am sorry for the late reply. I need the weights you trained to reproduce your results for our research.

**Comment by Mamadou-Keita** [comment]
Hi,

I update the repo with all the trained weights on different generative
models.

You can check it and let me know if you need something else.

Good luck.

Best regards.

Le ven. 4 oct. 2024 à 04:15, hoangsavitar ***@***.***> a
écrit :
